'use strict';
const COLORS={R:'#e83e58',P:'#ee55d5',B:'#8261eb',C:'#55d6e8',G:'#31b968',L:'#9ad94b',Y:'#ffd833',O:'#ff922f',T:'#a87363',D:'#56616d'};
const maps=[
['....PPPPPRRRRTTTT.......','...PPPPPPRRRRTTTTT......','..PPPPPPRRRRTTTTTTT.....','..PPPPRRRRRTTTTTTTTT....','.PPPPRRRRTTTTTTTTTTTT...','.RRRRTTTTTTTTTGGGGGG....','RRRRTTTTTTTTGGGGGGGGG...','TTTTTTTTTTGGGGGGGGGGGG..','TTTTTTTTTGGGGGGGGGGGGGG.','TTTTTTTTGGGGGGGGGGGGGGG.','TTTTYYYYYYYYYYYYYGGGGGGG.','TTTYYYYYYYYYYYYYYYYGGGGG.','TTYYYYYYYYYYYYYYYYYYTTTT.','TTTOOOOOOOOOOOOOOOOTTTT..','TTTOOOOOOOOOOOOOOOOTTT...','TTTRRRRRRRRRRRRRRRTTT....','..RRRRRRRRRRRRRRRR.......','...RRRRRRRRRRRRRR........','....RRRRRRRRRRRR.........','.....RRRRRRRRRR..........'],
['.........RRRR...........','.......RRRRRRRR.........','......RRRTTTTRRR.........','.....RRTTTTTTTTRR........','....RRTTYTTTYTTRR........','....RTTTTTTTTTTTR........','...RRTTTRRRRTTTRR........','...RTTTTRRRRTTTTR........','...RTTTTTTTTTTTTR........','...RRTTTTTTTTTTRR........','....RRGGGGGGGGRR.........','.....GGGGGGGGGG..........','....GGGGGGGGGGGG.........','...GGGGBGGGGBGGGG........','...GGGGBGGGGBGGGG........','....GGGB...BGGGG.........','....BBB.....BBB..........','...BBBB.....BBBB.........','........................','........................'],
['.......YYYYYY...........','......YYYYYYYY..........','.....YYOOOOOOYY.........','....YYOOOOOOOOYY........','...YYOOOYYYYOOOYY.......','...YOOYYYYYYYYOOY.......','..YYOYYYCCCCYYYOYY......','..YOOYYCCCCCCYYOOY......','..YOOYCCCCCCCCYOOY......','..YOOYYCCCCCCYYOOY......','...YOOYYCCCCYYOOY.......','...YYOOYYYYYYOOYY.......','....YYOOOOOOOOYY........','.....YYOOOOOOYY.........','......YYOOOOYY..........','.......YYOOYY...........','........YYYY............','.........YY.............','........GGGG............','.......GGGGGG...........']
];
const $=s=>document.querySelector(s),canvas=$('#board'),ctx=canvas.getContext('2d');
let level=Number(localStorage.getItem('nf-level')||0)%maps.length,grid,slots,stacks,processing=false,sound=localStorage.getItem('nf-sound')!=='off',audio,timer,particles=[];
function makeLevel(){grid=maps[level].map(r=>[...r]);slots=Array(5).fill(null);particles=[];const counts={};grid.flat().filter(x=>x!=='.').forEach(c=>counts[c]=(counts[c]||0)+1);let boxes=[];Object.entries(counts).forEach(([color,n])=>{while(n){const take=Math.min(n,18+Math.floor(Math.random()*13));boxes.push({color,count:take,id:crypto.randomUUID()});n-=take}});boxes.sort((a,b)=>depthFor(a.color)-depthFor(b.color)||Math.random()-.5);stacks=[[],[],[],[]];boxes.forEach((b,i)=>stacks[i%4].push(b));save();render();resize()}
function depthFor(color){let best=99;grid.forEach((row,r)=>row.forEach((v,c)=>{if(v===color)best=Math.min(best,Math.min(r,c,grid.length-1-r,row.length-1-c))}));return best}
function save(){localStorage.setItem('nf-level',level)}
function exposed(r,c){if(grid[r]?.[c]==='.'||grid[r]?.[c]==null)return false;return [[-1,0],[1,0],[0,-1],[0,1]].some(([dr,dc])=>grid[r+dr]?.[c+dc]==null||grid[r+dr][c+dc]==='.')}
function targets(color){const a=[];grid.forEach((row,r)=>row.forEach((v,c)=>{if(v===color&&exposed(r,c))a.push({r,c})}));return a}
function left(){return grid.flat().filter(x=>x!=='.').length}
function tapBox(col){if(processing||!stacks[col].length)return;const open=slots.indexOf(null);if(open<0){toast('All five colony slots are full');checkJam();return}slots[open]=stacks[col].shift();tone(330,.04);render();runColony()}
async function runColony(){if(processing)return;processing=true;let moved=true;while(moved){moved=false;for(let i=0;i<slots.length;i++){const box=slots[i];if(!box)continue;const t=targets(box.color)[0];if(t){moved=true;await carry(i,t);box.count--;grid[t.r][t.c]='.';if(box.count<=0)slots[i]=null;render();draw();if(!left()){processing=false;win();return}}} }processing=false;render();checkJam()}
function carry(slotIndex,t){return new Promise(resolve=>{const rect=canvas.getBoundingClientRect(),cell=rect.width/26,tx=(t.c+1.5)*cell,ty=(t.r+1.5)*cell;particles.push({color:slots[slotIndex].color,x:rect.width/2,y:rect.height+8,tx,ty,start:performance.now(),dur:170,resolve});animate()})}
function animate(now=performance.now()){let active=false;particles.forEach(p=>{if(p.done)return;const q=Math.min(1,(now-p.start)/p.dur),e=1-(1-q)*(1-q);p.cx=p.x+(p.tx-p.x)*e;p.cy=p.y+(p.ty-p.y)*e;if(q>=1){p.done=true;tone(520,.018);p.resolve()}else active=true});draw();particles=particles.filter(p=>!p.done);if(active)requestAnimationFrame(animate)}
function checkJam(){if(left()&&slots.every(Boolean)&&!slots.some(s=>targets(s.color).length)){showMessage('Colony jammed!','All five slots are holding colors the ants cannot reach.','Try again',makeLevel)}}
function win(){tone(720,.12);setTimeout(()=>tone(940,.18),120);showMessage('Picture cleared!','Your ants carried every block back to the nest.',level===maps.length-1?'Play again':'Next level',()=>{level=(level+1)%maps.length;makeLevel()})}
function showMessage(title,text,button,fn){$('#messageTitle').textContent=title;$('#messageText').textContent=text;$('#messageBtn').textContent=button;$('#messageBtn').onclick=()=>{$('#message').hidden=true;fn()};$('#message').hidden=false}
function render(){const slotEl=$('#slots');slotEl.innerHTML='';slots.forEach(s=>{const d=document.createElement('div');d.className='slot'+(s?' filled':'')+(s&&!targets(s.color).length?' waiting':'');if(s){d.style.setProperty('--c',COLORS[s.color]);d.innerHTML=`<b>🐜</b><small>${s.count}</small>`}slotEl.append(d)});const trays=$('#trays');trays.innerHTML='';stacks.forEach((stack,i)=>{const col=document.createElement('div');col.className='stack';if(!stack.length)col.innerHTML='<div class="empty-stack"></div>';stack.slice(0,4).reverse().forEach((b,rev)=>{const actual=Math.min(3,stack.length-1)-rev,btn=document.createElement('button');btn.className='box'+(actual===0&&targets(b.color).length?' safe':'');btn.style.setProperty('--c',COLORS[b.color]);btn.innerHTML=`${b.count}<small>${b.color}</small>`;if(actual===0)btn.onclick=()=>tapBox(i);col.append(btn)});trays.append(col)});$('#leftCount').textContent=left();$('#levelNo').textContent=level+1}
function resize(){const dpr=Math.min(devicePixelRatio||1,2),rect=canvas.getBoundingClientRect();canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function draw(){const rect=canvas.getBoundingClientRect(),w=rect.width,h=rect.height,cell=Math.min(w/26,h/22),ox=(w-24*cell)/2,oy=cell*.45;ctx.clearRect(0,0,w,h);ctx.fillStyle='#f8f0de';ctx.fillRect(0,0,w,h);grid.forEach((row,r)=>row.forEach((v,c)=>{if(v==='.')return;const x=ox+c*cell,y=oy+r*cell;ctx.fillStyle=COLORS[v];ctx.fillRect(x+.5,y+.5,cell-1,cell-1);ctx.fillStyle='#fff3';ctx.fillRect(x+1,y+1,cell-2,Math.max(1,cell*.22));ctx.strokeStyle='#5e362733';ctx.strokeRect(x+.5,y+.5,cell-1,cell-1)}));particles.forEach(p=>{if(p.done)return;ctx.fillStyle='#2e1b17';ctx.beginPath();ctx.arc(p.cx,p.cy,Math.max(2,cell*.16),0,Math.PI*2);ctx.fill();ctx.strokeStyle=COLORS[p.color];ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.cx-4,p.cy-3);ctx.lineTo(p.cx+4,p.cy+3);ctx.stroke()})}
function tone(f,d){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=.025;o.connect(g).connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.stop(audio.currentTime+d)}catch{}}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>e.classList.remove('show'),1400)}
$('#restart').onclick=makeLevel;$('#next').onclick=()=>{level=(level+1)%maps.length;makeLevel()};$('#sound').onclick=()=>{sound=!sound;localStorage.setItem('nf-sound',sound?'on':'off');$('#sound').textContent=sound?'♪':'×'};window.addEventListener('resize',resize);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');makeLevel();
